### ISSUE TITLE
Duplicate entry in push_subscriptions_endpoint_unique

### ISSUE THREAD

**Issue by notflip** [laravel-notification-channels/webpush#143]
I'm getting the following error
`PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'https://fcm.googleapis.com/fcm/send/ffhNT2LJu7U:APA91bFnpKFN0KOA' for key 'push_subscriptions_endpoint_unique'`

Is this supposed to happen? I did not modify the migration that comes with the package.

**Comment by shehi** [comment]
Make sure you let only ONE user to subscribe on the same browser profile. Browser profiles should be unique, because after all, browsers in the context of PNs are just devices. In PN world, devices are unique recipients of notifications.

When a user subs to PNs, check if endpoint exists already. If it does, tell them that browser profile is already used.
