### ISSUE TITLE
Any reason why column "endpoint" is unique?

### ISSUE THREAD

**Issue by dnsnx** [laravel-notification-channels/webpush#165]
A question came up today:
I was wondering today, that the column `endpoint` in DB is `unique`. 
Are there any special reasons for this? 
I tried with multiple / same endpoint entries and it works all fine... Why the limitation?

**Comment by beatkey** [comment]
I got this error "SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `push_subscriptions` add unique `push_subscriptions_endpoint_unique`(`endpoint`))" and i removed unique for fix error.

**Comment by shehi** [comment]
Endpoints should be unique because messages are user-based. On the same browser session profile 2 different users can't and shouldn't subscribe to the same push notification service. Otherwise it'd be a mess: which will receive the notification? Both?

That's why it is a good idea to notify ("slash-educate") your userbase to use different profiles for PN subscription, or not offer them it at all.

Additionally, take care of removing "expired" PN endpoints (happens when users block PNs which were working before). Browser [MAY (big MAY here) tell you](https://github.com/w3c/push-api/issues/116#issuecomment-280743159) (via `pushsubscriptionchange` event) when expiration happens, but even in that case, [it won't tell you what endpoint is it that expired](https://blog.pushpad.xyz/2016/05/the-push-api-and-its-wild-unsubscription-mechanism/). So the only way to handle this situation is to push, when it fails expire that endpoint right there and then (and possibly offer a resubscription).

All in all, yes, `endpoint` field should be unique. It literally is an individual address of PN recipient (where only 1 person should reside - similar to personal email addresses, only one physical person is a recipient).
