### ISSUE TITLE
Rows Deleted

### ISSUE THREAD

**Issue by ahmedalmulki** [laravel-notification-channels/webpush#60]
Hi, I have an issue, when I send the notification to all users some rows deleted in the push_subscriptions table without any reason, including my mobile maybe I was turning off the internet when the notification sent , and when I compare users table and push_subscriptions table I found more than 80 records missing, please how can I disable the deletion procedures in push_subscriptions?

**Comment by cretueusebiu** [comment]
The subscriptions are deleted [here](https://github.com/laravel-notification-channels/webpush/blob/master/src/WebPushChannel.php#L50) when are invalid.

**Comment by ahmedalmulki** [comment]
Can I override this?  because the record will be deleted if they do not have any internet connection also, and in my opinion, it's not right.

**Comment by cretueusebiu** [comment]
You'll have to override the service provider and the `WebPushChannel` class.

I think it should check for more specific errors.

https://github.com/web-push-libs/web-push-php#server-errors
https://autopush.readthedocs.io/en/latest/http.html#errors
https://developers.google.com/web/fundamentals/push-notifications/common-issues-and-reporting-bugs

**Comment by ahmedalmulki** [comment]
Hi, I tried to comment on this [line](https://github.com/laravel-notification-channels/webpush/blob/master/src/WebPushChannel.php#L50) to test it out, but even after that, there are some deleted records after sending the notifications !!!

**Comment by ahmedalmulki** [comment]
Hi, I am still facing the same problem even after removing this [line](https://github.com/laravel-notification-channels/webpush/blob/master/src/WebPushChannel.php#L50), could you please tell me how can I fix that, I am losing many records!

**Comment by pimhooghiemstra** [comment]
@ahmedalmulki I noticed the exact same thing. It turned out that I forgot to add the VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY in my .env file.

Somehow, the artisan command responsible for putting them there in the first place only added one of them in the .env file. 

By studying the code I found out that the artisan command can take an additional argument --show to put the keys in the terminal instead of in .env. I used this to generate them and copied them over myself.

> php artisan webpush:vapid --show

When I deployed my app to the server, I forgot to update my .env file over there. The records fomr table push_subscriptions were removed. I realize now that was due to invalids as @cretueusebiu said.

**Comment by ahmedalmulki** [comment]
@cretueusebiu  is there any news regarding this issue?

**Comment by patrickpietens** [comment]
I made a PR (https://github.com/laravel-notification-channels/webpush/pull/72) which fixes this issue. According to Google's documentation (https://developers.google.com/web/fundamentals/push-notifications/common-issues-and-reporting-bugs#http_status_codes) we need to delete a subscription when the server responds with a 404 or 410 HTTP status code.

I hope this solves the problem.

**Comment by frumentius** [comment]
@cretueusebiu HI, I also got this issue of deleted record of user subscription from my database and not getting the notification. So by reading from this thread I assume this happen because somehow it failed whilst trying to connect to the endpoint. So first where and how to get the error log for this so to make sure that assumption is correct, and second what cause it to failed to connect to perfectly valid endpoint?

**Comment by cretueusebiu** [comment]
https://github.com/laravel-notification-channels/webpush/commit/f32e186b57347b5c701904be73745943cdf5a7b6 adds a report handler that can be changed.
